# Generated by Django 2.1.5 on 2019-06-13 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
        ('questApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Сумма с комиссией')),
                ('value_wo', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Сумма без комиссии')),
                ('method', models.CharField(max_length=256, verbose_name='ID способа оплаты')),
                ('payment_id', models.CharField(max_length=256, verbose_name='ID заказа')),
                ('agreement', models.CharField(max_length=256, verbose_name='ID соглашения')),
                ('date_created', models.DateTimeField(verbose_name='Дата оплаты')),
                ('is_is_awarding_time', models.BooleanField(default=False, verbose_name='Во время розыгрыша')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='player.Player', verbose_name='Пользователь')),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='questApp.Quest', verbose_name='Квест')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('player', 'quest')},
        ),
    ]
