# Generated by Django 2.1.5 on 2020-04-07 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='is_is_awarding_time',
            new_name='is_awarding_time',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='value',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='value_wo',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Сумма к оплате'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='date_pay',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='profit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Зачисленино на ваш счет'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='ID заказа'),
        ),
    ]
