# Generated by Django 2.1.5 on 2019-06-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='awarding_descr',
            field=models.TextField(blank=True, default='', max_length=4096, null=True, verbose_name='Описание розыгрыша'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='description',
            field=models.TextField(blank=True, default='', max_length=4096, null=True, verbose_name='Описание'),
        ),
    ]
