# Generated by Django 2.1.5 on 2019-06-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questApp', '0002_auto_20190613_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='image_award',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/', verbose_name='Картинка перед описанием розыгрыша:'),
        ),
        migrations.AddField(
            model_name='quest',
            name='image_descr',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/', verbose_name='Картинка перед описанием:'),
        ),
        migrations.AddField(
            model_name='step',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/', verbose_name='Картинка:'),
        ),
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.TextField(max_length=4096, verbose_name='Текст:\nтекст_текст~время\n'),
        ),
    ]
