# Generated by Django 2.1.5 on 2019-07-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questApp', '0004_auto_20190625_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='image_award',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Картинку в описании розыгрыша:'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='image_descr',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Картинку в описании квеста:'),
        ),
        migrations.AlterField(
            model_name='step',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на картинку:'),
        ),
    ]
