# Generated by Django 2.1.5 on 2019-07-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questApp', '0005_auto_20190704_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='vk_image_award',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='vk_image_award'),
        ),
        migrations.AddField(
            model_name='quest',
            name='vk_image_descr',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='vk_image_descr'),
        ),
    ]
