# Generated by Django 2.1.5 on 2019-07-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questApp', '0006_auto_20190704_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='vk_image',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='vk_image'),
        ),
    ]
