# Generated by Django 2.1.5 on 2019-08-27 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questApp', '0007_step_vk_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersquestcompleted',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_quests_completed', to='questApp.Option', verbose_name='Вариант ответа'),
        ),
    ]
