# Generated by Django 2.1.5 on 2020-03-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questApp', '0008_playersquestcompleted_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.TextField(max_length=4096, verbose_name='Текст:\nтекст~время_текст~время\n'),
        ),
    ]
