# Generated by Django 2.1.5 on 2020-04-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questApp', '0010_auto_20200403_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersquest',
            name='attempts_num',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество попыток'),
        ),
    ]
