# Generated by Django 2.1.5 on 2020-04-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questApp', '0011_auto_20200403_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='date_sale_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания продажи'),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(db_index=True, max_length=256, verbose_name='Текст опции'),
        ),
    ]
