# Generated by Django 2.1.5 on 2020-06-21 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0012_auto_20200621_1630'),
        ('questApp', '0012_auto_20200407_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questpermittedplayers',
            options={'verbose_name': 'Доступ к квесту', 'verbose_name_plural': 'Доступы к квестам'},
        ),
        migrations.AddField(
            model_name='questpermittedplayers',
            name='player',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='player.Player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quest',
            name='players_with_access',
            field=models.ManyToManyField(related_name='permitted_quests', through='questApp.QuestPermittedPlayers', to='player.Player'),
        ),
        migrations.RemoveField(
            model_name='questpermittedplayers',
            name='players_quest',
        ),
        migrations.AlterUniqueTogether(
            name='questpermittedplayers',
            unique_together={('quest', 'player')},
        ),
    ]
