# Generated by Django 2.1.5 on 2019-06-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_next_message_contact',
            field=models.BooleanField(default=False, verbose_name='Следующее сообщение - Контакт для связи'),
        ),
        migrations.AlterField(
            model_name='player',
            name='tg_name',
            field=models.CharField(blank=True, default='Нет контакта для связи', max_length=256, null=True, verbose_name='Telegram логин/Контакт для связи'),
        ),
    ]
