# Generated by Django 2.1.5 on 2019-06-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20190616_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='tg_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='tg_name',
        ),
        migrations.AddField(
            model_name='player',
            name='user_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='User id'),
        ),
        migrations.AddField(
            model_name='player',
            name='user_login',
            field=models.CharField(blank=True, default='Нет контакта для связи', max_length=256, null=True, verbose_name='Логин/Контакт для связи'),
        ),
    ]
