# Generated by Django 2.1.5 on 2019-06-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20190625_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='user_id',
            field=models.CharField(default=1, max_length=256, unique=True, verbose_name='User id'),
            preserve_default=False,
        ),
    ]
