# Generated by Django 2.1.5 on 2019-06-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20190627_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_next_message_referral',
            field=models.BooleanField(default=False, verbose_name='Следующее сообщение - Пригласивший'),
        ),
        migrations.AddField(
            model_name='player',
            name='player_type',
            field=models.CharField(default='TG', max_length=256, verbose_name='Тип пользователя'),
            preserve_default=False,
        ),
    ]
