# Generated by Django 2.1.5 on 2019-06-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_auto_20190630_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_next_message_referral',
            field=models.BooleanField(default=True, verbose_name='Следующее сообщение - Пригласивший'),
        ),
    ]
