# Generated by Django 2.1.5 on 2019-07-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_auto_20190630_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_next_message_referral',
            field=models.BooleanField(default=False, verbose_name='Следующее сообщение - Пригласивший'),
        ),
    ]
