# Generated by Django 2.1.5 on 2019-08-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_auto_20190704_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Повышенные права'),
        ),
    ]
