# Generated by Django 2.1.5 on 2019-08-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_player_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Повышенные права'),
        ),
    ]
