# Generated by Django 2.1.5 on 2020-03-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_auto_20190827_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Повышенные права'),
        ),
    ]
