# Generated by Django 2.1.5 on 2020-04-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0010_auto_20200321_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='add_contact',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Доп. Контакт для связи'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user_login',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Логин/Контакт для связи'),
        ),
    ]
