# Generated by Django 2.1.5 on 2020-06-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0011_auto_20200403_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Имя пользователя 1'),
        ),
        migrations.AddField(
            model_name='player',
            name='second_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Имя пользователя 2'),
        ),
    ]
