"""
Django settings for tgBot project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# TODO: Change to False before pushing to prod
DEBUG = True

# if DEBUG:
#     LOGGING = {
#         'version': 1,
#         'disable_existing_loggers': False,
#         'handlers': {
#             'console': {
#                 'level': 'DEBUG',
#                 'class': 'logging.StreamHandler',
#             }
#         },
#         'loggers': {
#             'django.db.backends': {
#                 'handlers': ['console'],
#                 'level': 'DEBUG',
#             },
#         }
#     }

ALLOWED_HOSTS = ["*"]

SITE_URL = "http://91.245.226.181"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    'constance',
    'constance.backends.database',

    # Custom apps
    "questApp",
    # "payment",
    "player",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "tgBot.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tgBot.wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

if DEBUG:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql_psycopg2",
            "NAME": "tgquest",
            "USER": "questbot",
            "PASSWORD": os.environ.get("POSTGRESQL_DB_PASSWORD"),
            "HOST": "localhost",
            "PORT": "",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = "ru-RU"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_L10N = True

# USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "static/")
STATIC_URL = "/static/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media/")
MEDIA_URL = "/media/"

# Telegram-bot
BOT_TG_ID = "@"

# Telegram API

if DEBUG:
    BOT_TG_ID += "Quest_teshyu_bot"
    TG_ACCESS_TOKEN = os.environ.get("TG_ACCESS_TOKEN")
    TG_PROXY_URL = "http://155.138.148.76:8080"
    VK_ACCESS_TOKEN = os.environ.get("VK_ACCESS_TOKEN")
    VK_GROUP_ID = "130703093"
else:
    BOT_TG_ID += "indecent_quests_bot"
    TG_ACCESS_TOKEN = os.environ.get("TG_ACCESS_TOKEN")
    TG_PROXY_URL = ""
    VK_ACCESS_TOKEN = os.environ.get("VK_ACCESS_TOKEN")
    VK_GROUP_ID = "164636367"

TG_JOIN_URL = "https://teleg.run/"

CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

CONSTANCE_CONFIG = {
    "MY_GAMES": ("Мои квесты", " "),
    "ALL_GAMES": ("Все квесты", " "),
    "MAIN_MENU": ("Главное меню", " "),
    "ASK_TO_RESTART": ("Начать заново", " "),
    "CONFIRM_TO_RESTART": ("Да, начать заново", " "),
    "RETURN_TO_GAME": ("Вернуться в игру", " "),
    "START_WO_REFERRER": ("Пропустить", " "),
    "START_GAME": ("Начать игру", " "),
    "SETTINGS": ("Настройки", " "),
    "CANCEL_CONTACT": ("Отменить контакт", " "),
    "ADD_CONTACT": ("Добавить контакт", " "),
    "MAIN_MENU_TEXT": ("Главное меню\n", " "),
    "GAME_WIN_TEXT": ('Вы победили! Чтобы с вами можно было связаться, задайте контакт для связи в меню ', " "),
    "GAME_LOST_TEXT": ("Вы проиграли.", " "),
    "GAME_START_BUTTON": ('Чтобы начать игру нажмите', " "),
    "BUY_LINK_TEXT": ("Ссылка для покупки квеста:", " "),
    "QUEST_IS_NOT_AVAILABLE": ("Квест недоступен", " "),
    "QUEST_IS_ON_AWARDING": ("Этот квест находится в розыгрыше!", " "),
    "QUEST_DESCRIPTION": ("Описание квеста:", " "),
    "QUEST_CONFIRM_RESTART": ("Вы уверены, что хотите начать игру заново?", " "),
    "QUEST_ASK_RESTART": ('Чтобы начать игру заново, нажмите', " "),
    "QUEST_ATTEMPTS_EXCEEDED": ("Вы больше не можете продолжать этот квест", " "),
    "QUESTS_ALL": ("Список всех квестов:", " "),
    "PLAYER_QUESTS_LIST": ("Список ваших квестов:", " "),
    "PLAYER_NO_QUESTS": ("В данный момент вы не проходите ни один квест.", " "),
    "PLAYER_PLAYING": ("В данный момент вы проходите квест:", " "),
    "PLAYER_REFERRAL": ("Это ваша реферальная ссылка. Отправьте её другу!", " "),
    "PLAYER_REFERRAL_SET": ("Вы успешно задали пригласившего пользователя", " "),
    "PLAYER_CONTACT": ("Нынешний контакт для связи с вами:", " "),
    "PLAYER_CONTACT_SET": ("Чтобы задать контакт для связи отправьте его следующим сообщением", " "),
    "PLAYER_CONTACT_SET_DONE": ("Вы задали новый контакт для связи", " ",)
}

CACHING_TIMEOUTS = {
    "STEP": {"TIMEOUT": 60 * 5},
    "OPTION": {"TIMEOUT": 60 * 5},
    "QUEST": {"TIMEOUT": 60 * 5},
    "PLAYER_QUEST": {"TIMEOUT": 60 * 5},
    "PLAYER": {"TIMEOUT": 60 * 5},
}


BOT_MENU = {
    "MY_GAMES": "🎮",
    "BUY_GAME": "💰",
    "ALL_GAMES": "🎲",
    "MAIN_MENU": "⚽",
    "ASK_TO_RESTART": "♻️",
    "CONFIRM_TO_RESTART": "♻️",
    "RETURN_TO_GAME": "⏪",
    "START_WO_REFERRER": "⏩",
    "START_GAME": "🏁",
    "SETTINGS": "🛠️",
    "CANCEL_CONTACT": "❌",
    "ADD_CONTACT": "📱",
    "GAME": "♟️",
}
